#!/usr/bin/env python3
"""
Generate Exponential LUT for Softmax Hardware Implementation

This script generates a lookup table for exp(x) in Q15 fixed-point format.
The LUT covers the range [-8, 0] mapped to 256 entries.

Output format: Verilog $readmemh compatible hex file

Author: Generated for streaming-attention-accelerator project
Date: 2026-04-03
"""

import numpy as np
import os

def generate_exp_lut(num_entries=256, x_min=-8.0, x_max=0.0):
    """
    Generate exponential LUT in Q15 format.

    Args:
        num_entries: Number of LUT entries (default 256)
        x_min: Minimum input value (default -8.0)
        x_max: Maximum input value (default 0.0)

    Returns:
        lut: Array of Q15 fixed-point values
    """
    # Generate input values
    x_values = np.linspace(x_min, x_max, num_entries)

    # Compute exp(x)
    exp_values = np.exp(x_values)

    # Convert to Q15 format (scale by 2^15 = 32768)
    q15_values = np.round(exp_values * 32768).astype(np.int32)

    # Clamp to valid Q15 range [0, 32767]
    q15_values = np.clip(q15_values, 0, 32767)

    return q15_values, x_values, exp_values

def write_verilog_hex(lut, filename):
    """Write LUT to Verilog hex file format."""
    with open(filename, 'w') as f:
        for value in lut:
            f.write(f"{value:04x}\n")

def write_verilog_init(lut, filename):
    """Write LUT as Verilog initial block."""
    with open(filename, 'w') as f:
        f.write("// Exponential LUT for softmax\n")
        f.write("// Format: Q15 fixed-point (16-bit)\n")
        f.write("// Range: exp(-8) to exp(0)\n")
        f.write("// Generated by generate_exp_lut.py\n\n")
        f.write("initial begin\n")
        for i, value in enumerate(lut):
            if i % 4 == 0:
                f.write("    ")
            f.write(f"exp_lut[{i:3d}] = 16'h{value:04x};")
            if i % 4 == 3:
                f.write("\n")
            else:
                f.write(" ")
        if len(lut) % 4 != 0:
            f.write("\n")
        f.write("end\n")

def print_summary(lut, x_values, exp_values):
    """Print summary statistics."""
    print("=" * 70)
    print("Exponential LUT Generation Summary")
    print("=" * 70)
    print(f"Number of entries: {len(lut)}")
    print(f"Input range:       [{x_values[0]:.3f}, {x_values[-1]:.3f}]")
    print(f"Output range:      [{lut[0]}, {lut[-1]}] (Q15)")
    print(f"                   [{exp_values[0]:.6f}, {exp_values[-1]:.6f}] (float)")
    print()
    print("Sample values:")
    print(f"  x = {x_values[0]:.3f}  → exp(x) = {exp_values[0]:.6f}  → Q15 = {lut[0]:5d} (0x{lut[0]:04x})")
    print(f"  x = {x_values[128]:.3f} → exp(x) = {exp_values[128]:.6f}  → Q15 = {lut[128]:5d} (0x{lut[128]:04x})")
    print(f"  x = {x_values[-1]:.3f}  → exp(x) = {exp_values[-1]:.6f}  → Q15 = {lut[-1]:5d} (0x{lut[-1]:04x})")
    print()
    print("Verification:")
    print(f"  exp(-8) ≈ 0.000335 → Q15 = {int(0.000335 * 32768)} (expected)")
    print(f"  exp(-8) → Q15 = {lut[0]} (generated)")
    print(f"  exp(0)  = 1.0      → Q15 = 32768 (expected)")
    print(f"  exp(0)  → Q15 = {lut[-1]} (generated)")
    print("=" * 70)

def main():
    # Create output directory
    output_dir = "../../mem"
    os.makedirs(output_dir, exist_ok=True)

    # Generate LUT
    print("Generating exponential LUT...")
    lut, x_values, exp_values = generate_exp_lut()

    # Write files
    hex_file = os.path.join(output_dir, "exp_lut.hex")
    init_file = os.path.join(output_dir, "exp_lut_init.v")

    write_verilog_hex(lut, hex_file)
    write_verilog_init(lut, init_file)

    print(f"✓ Hex file written:  {hex_file}")
    print(f"✓ Init file written: {init_file}")
    print()

    # Print summary
    print_summary(lut, x_values, exp_values)

if __name__ == "__main__":
    main()
