// Exponential LUT for softmax
// Format: Q15 fixed-point (16-bit)
// Range: exp(-8) to exp(0)
// Generated by generate_exp_lut.py

initial begin
    exp_lut[  0] = 16'h000b; exp_lut[  1] = 16'h000b; exp_lut[  2] = 16'h000c; exp_lut[  3] = 16'h000c;
    exp_lut[  4] = 16'h000c; exp_lut[  5] = 16'h000d; exp_lut[  6] = 16'h000d; exp_lut[  7] = 16'h000e;
    exp_lut[  8] = 16'h000e; exp_lut[  9] = 16'h000f; exp_lut[ 10] = 16'h000f; exp_lut[ 11] = 16'h0010;
    exp_lut[ 12] = 16'h0010; exp_lut[ 13] = 16'h0011; exp_lut[ 14] = 16'h0011; exp_lut[ 15] = 16'h0012;
    exp_lut[ 16] = 16'h0012; exp_lut[ 17] = 16'h0013; exp_lut[ 18] = 16'h0013; exp_lut[ 19] = 16'h0014;
    exp_lut[ 20] = 16'h0015; exp_lut[ 21] = 16'h0015; exp_lut[ 22] = 16'h0016; exp_lut[ 23] = 16'h0017;
    exp_lut[ 24] = 16'h0017; exp_lut[ 25] = 16'h0018; exp_lut[ 26] = 16'h0019; exp_lut[ 27] = 16'h001a;
    exp_lut[ 28] = 16'h001a; exp_lut[ 29] = 16'h001b; exp_lut[ 30] = 16'h001c; exp_lut[ 31] = 16'h001d;
    exp_lut[ 32] = 16'h001e; exp_lut[ 33] = 16'h001f; exp_lut[ 34] = 16'h0020; exp_lut[ 35] = 16'h0021;
    exp_lut[ 36] = 16'h0022; exp_lut[ 37] = 16'h0023; exp_lut[ 38] = 16'h0024; exp_lut[ 39] = 16'h0025;
    exp_lut[ 40] = 16'h0027; exp_lut[ 41] = 16'h0028; exp_lut[ 42] = 16'h0029; exp_lut[ 43] = 16'h002a;
    exp_lut[ 44] = 16'h002c; exp_lut[ 45] = 16'h002d; exp_lut[ 46] = 16'h002f; exp_lut[ 47] = 16'h0030;
    exp_lut[ 48] = 16'h0032; exp_lut[ 49] = 16'h0033; exp_lut[ 50] = 16'h0035; exp_lut[ 51] = 16'h0036;
    exp_lut[ 52] = 16'h0038; exp_lut[ 53] = 16'h003a; exp_lut[ 54] = 16'h003c; exp_lut[ 55] = 16'h003e;
    exp_lut[ 56] = 16'h0040; exp_lut[ 57] = 16'h0042; exp_lut[ 58] = 16'h0044; exp_lut[ 59] = 16'h0046;
    exp_lut[ 60] = 16'h0048; exp_lut[ 61] = 16'h004b; exp_lut[ 62] = 16'h004d; exp_lut[ 63] = 16'h004f;
    exp_lut[ 64] = 16'h0052; exp_lut[ 65] = 16'h0054; exp_lut[ 66] = 16'h0057; exp_lut[ 67] = 16'h005a;
    exp_lut[ 68] = 16'h005d; exp_lut[ 69] = 16'h0060; exp_lut[ 70] = 16'h0063; exp_lut[ 71] = 16'h0066;
    exp_lut[ 72] = 16'h0069; exp_lut[ 73] = 16'h006d; exp_lut[ 74] = 16'h0070; exp_lut[ 75] = 16'h0074;
    exp_lut[ 76] = 16'h0077; exp_lut[ 77] = 16'h007b; exp_lut[ 78] = 16'h007f; exp_lut[ 79] = 16'h0083;
    exp_lut[ 80] = 16'h0087; exp_lut[ 81] = 16'h008c; exp_lut[ 82] = 16'h0090; exp_lut[ 83] = 16'h0095;
    exp_lut[ 84] = 16'h0099; exp_lut[ 85] = 16'h009e; exp_lut[ 86] = 16'h00a3; exp_lut[ 87] = 16'h00a8;
    exp_lut[ 88] = 16'h00ae; exp_lut[ 89] = 16'h00b3; exp_lut[ 90] = 16'h00b9; exp_lut[ 91] = 16'h00bf;
    exp_lut[ 92] = 16'h00c5; exp_lut[ 93] = 16'h00cb; exp_lut[ 94] = 16'h00d2; exp_lut[ 95] = 16'h00d9;
    exp_lut[ 96] = 16'h00df; exp_lut[ 97] = 16'h00e7; exp_lut[ 98] = 16'h00ee; exp_lut[ 99] = 16'h00f5;
    exp_lut[100] = 16'h00fd; exp_lut[101] = 16'h0105; exp_lut[102] = 16'h010e; exp_lut[103] = 16'h0116;
    exp_lut[104] = 16'h011f; exp_lut[105] = 16'h0128; exp_lut[106] = 16'h0132; exp_lut[107] = 16'h013b;
    exp_lut[108] = 16'h0146; exp_lut[109] = 16'h0150; exp_lut[110] = 16'h015b; exp_lut[111] = 16'h0166;
    exp_lut[112] = 16'h0171; exp_lut[113] = 16'h017d; exp_lut[114] = 16'h0189; exp_lut[115] = 16'h0195;
    exp_lut[116] = 16'h01a2; exp_lut[117] = 16'h01b0; exp_lut[118] = 16'h01bd; exp_lut[119] = 16'h01cc;
    exp_lut[120] = 16'h01da; exp_lut[121] = 16'h01e9; exp_lut[122] = 16'h01f9; exp_lut[123] = 16'h0209;
    exp_lut[124] = 16'h021a; exp_lut[125] = 16'h022b; exp_lut[126] = 16'h023d; exp_lut[127] = 16'h024f;
    exp_lut[128] = 16'h0262; exp_lut[129] = 16'h0275; exp_lut[130] = 16'h0289; exp_lut[131] = 16'h029e;
    exp_lut[132] = 16'h02b3; exp_lut[133] = 16'h02c9; exp_lut[134] = 16'h02e0; exp_lut[135] = 16'h02f7;
    exp_lut[136] = 16'h0310; exp_lut[137] = 16'h0329; exp_lut[138] = 16'h0342; exp_lut[139] = 16'h035d;
    exp_lut[140] = 16'h0378; exp_lut[141] = 16'h0395; exp_lut[142] = 16'h03b2; exp_lut[143] = 16'h03d0;
    exp_lut[144] = 16'h03ef; exp_lut[145] = 16'h040f; exp_lut[146] = 16'h0430; exp_lut[147] = 16'h0453;
    exp_lut[148] = 16'h0476; exp_lut[149] = 16'h049a; exp_lut[150] = 16'h04c0; exp_lut[151] = 16'h04e6;
    exp_lut[152] = 16'h050e; exp_lut[153] = 16'h0538; exp_lut[154] = 16'h0562; exp_lut[155] = 16'h058e;
    exp_lut[156] = 16'h05bc; exp_lut[157] = 16'h05ea; exp_lut[158] = 16'h061b; exp_lut[159] = 16'h064c;
    exp_lut[160] = 16'h0680; exp_lut[161] = 16'h06b5; exp_lut[162] = 16'h06eb; exp_lut[163] = 16'h0724;
    exp_lut[164] = 16'h075e; exp_lut[165] = 16'h079a; exp_lut[166] = 16'h07d8; exp_lut[167] = 16'h0818;
    exp_lut[168] = 16'h085a; exp_lut[169] = 16'h089f; exp_lut[170] = 16'h08e5; exp_lut[171] = 16'h092d;
    exp_lut[172] = 16'h0978; exp_lut[173] = 16'h09c6; exp_lut[174] = 16'h0a15; exp_lut[175] = 16'h0a68;
    exp_lut[176] = 16'h0abc; exp_lut[177] = 16'h0b14; exp_lut[178] = 16'h0b6e; exp_lut[179] = 16'h0bcc;
    exp_lut[180] = 16'h0c2c; exp_lut[181] = 16'h0c8f; exp_lut[182] = 16'h0cf6; exp_lut[183] = 16'h0d5f;
    exp_lut[184] = 16'h0dcc; exp_lut[185] = 16'h0e3d; exp_lut[186] = 16'h0eb1; exp_lut[187] = 16'h0f29;
    exp_lut[188] = 16'h0fa5; exp_lut[189] = 16'h1024; exp_lut[190] = 16'h10a8; exp_lut[191] = 16'h1130;
    exp_lut[192] = 16'h11bc; exp_lut[193] = 16'h124d; exp_lut[194] = 16'h12e2; exp_lut[195] = 16'h137c;
    exp_lut[196] = 16'h141b; exp_lut[197] = 16'h14bf; exp_lut[198] = 16'h1569; exp_lut[199] = 16'h1617;
    exp_lut[200] = 16'h16cc; exp_lut[201] = 16'h1785; exp_lut[202] = 16'h1845; exp_lut[203] = 16'h190b;
    exp_lut[204] = 16'h19d8; exp_lut[205] = 16'h1aab; exp_lut[206] = 16'h1b84; exp_lut[207] = 16'h1c65;
    exp_lut[208] = 16'h1d4c; exp_lut[209] = 16'h1e3b; exp_lut[210] = 16'h1f32; exp_lut[211] = 16'h2030;
    exp_lut[212] = 16'h2137; exp_lut[213] = 16'h2246; exp_lut[214] = 16'h235e; exp_lut[215] = 16'h247e;
    exp_lut[216] = 16'h25a8; exp_lut[217] = 16'h26db; exp_lut[218] = 16'h2818; exp_lut[219] = 16'h295f;
    exp_lut[220] = 16'h2ab1; exp_lut[221] = 16'h2c0d; exp_lut[222] = 16'h2d75; exp_lut[223] = 16'h2ee7;
    exp_lut[224] = 16'h3066; exp_lut[225] = 16'h31f1; exp_lut[226] = 16'h3389; exp_lut[227] = 16'h352d;
    exp_lut[228] = 16'h36df; exp_lut[229] = 16'h389e; exp_lut[230] = 16'h3a6c; exp_lut[231] = 16'h3c49;
    exp_lut[232] = 16'h3e35; exp_lut[233] = 16'h4030; exp_lut[234] = 16'h423c; exp_lut[235] = 16'h4459;
    exp_lut[236] = 16'h4686; exp_lut[237] = 16'h48c6; exp_lut[238] = 16'h4b17; exp_lut[239] = 16'h4d7c;
    exp_lut[240] = 16'h4ff4; exp_lut[241] = 16'h5280; exp_lut[242] = 16'h5521; exp_lut[243] = 16'h57d8;
    exp_lut[244] = 16'h5aa5; exp_lut[245] = 16'h5d88; exp_lut[246] = 16'h6083; exp_lut[247] = 16'h6397;
    exp_lut[248] = 16'h66c3; exp_lut[249] = 16'h6a0a; exp_lut[250] = 16'h6d6b; exp_lut[251] = 16'h70e7;
    exp_lut[252] = 16'h7481; exp_lut[253] = 16'h7837; exp_lut[254] = 16'h7c0c; exp_lut[255] = 16'h7fff;
end
